uk =
  signIn: "Увійти"
  signin: "Увійти"
  signOut: "Вийти"
  signUp: "Реєстрація"
  OR: "АБО"
  forgotPassword: "Забули пароль?"
  emailAddress: "Email"
  emailResetLink: "Відправити посилання для збросу"
  dontHaveAnAccount: "Немає аккаунта?"
  resetYourPassword: "Збросити пароль"
  updateYourPassword: "Обновити пароль"
  password: "Пароль"
  usernameOrEmail: "Ім'я користувача або email"
  email: "Email"
  ifYouAlreadyHaveAnAccount: "Якщо у вас вже є аккаунт"
  signUpWithYourEmailAddress: "Зареєструйтесь з вашою email адресою"
  username: "Ім'я користувача"
  optional: "Необов'язково"
  signupCode: "Реєстраційний код"
  clickAgree: "Натиснувши на Реєстрація ви погоджуєтесь з умовами"
  privacyPolicy: "Політики безпеки"
  terms: "Умовами користування"
  sign: "Підпис"
  configure: "Конфігурувати"
  with: "через"
  createAccount: "Створити аккаунт"
  and: "та"
  "Match failed":  "Не співпадають"
  "User not found":  "Користувача не знайдено"

  error:
    minChar: "Мінімальна кількість символів для паролю 7."
    pwOneLetter: "В паролі повинна буту хоча б одна буква."
    pwOneDigit: "В паролі повинна бути хоча б одна цифра."
    usernameRequired: "Ім'я користувача обов'язкове."
    emailRequired: "Email обов'язкове."
    signupCodeRequired: "Необхідний реєстраційний код."
    signupCodeIncorrect: "Некоректний реєстраційний код."
    signInRequired: "Для продовження необхідно ввійти."
    usernameIsEmail: "Ім'я користувача не може бути email."

T9n.map "uk", uk
